import AppKit
import os

/// A small motion a character can perform while it's peeked out.
///
/// The source art ships no gesture animations, so these sequences were
/// generated by isolating a body part and rotating it about its joint
/// (see Scripts/gen_gestures.py). Every sequence begins and ends on the
/// exact idle_00 pose, which lets playback cut in and out of the idle
/// loop with no visible jump.
enum Gesture: String, CaseIterable {
    case earLeft = "earL"
    case earRight = "earR"
    case paw

    var resourcePrefix: String { "gesture_\(rawValue)" }

    /// How much of the character has to be on screen for this gesture to
    /// be visible. The ears are up top and show at rest; the arms sit
    /// below the resting cut, so a paw wave needs the character to lean
    /// further out.
    var requiredReveal: CGFloat {
        switch self {
        case .earLeft, .earRight: return PeekLayoutBuilder.restRevealFraction
        case .paw: return PeekLayoutBuilder.maxRevealFraction
        }
    }

    /// Gestures grouped so one flavour of motion isn't over-represented —
    /// the two ear flicks look nearly alike, so they share a slot.
    static let families: [[Gesture]] = [[.earLeft, .earRight], [.paw]]
}

/// Which face a character is wearing. Picked per peek and then held for
/// that peek's whole life, so clicking never changes the expression
/// mid-animation. Each face has its own idle loop and gesture set.
enum FaceVariant: String, CaseIterable {
    case plain
    case smiling
}

/// Loads each species' idle frames and gesture sequences once, and hands
/// them out unmodified.
///
/// Rotation and flipping are deliberately *not* baked in here: doing so
/// would rasterize the art at a single fixed scale, which looks wrong on
/// a mixed-DPI multi-display setup. The view applies those transforms
/// instead, so each display renders at its own native resolution.
final class SpriteLibrary {
    static let shared = SpriteLibrary()

    private var idleFrames: [String: [NSImage]] = [:]      // "species|face"
    private var gestureFrames: [String: [NSImage]] = [:]   // "species|face|gesture"
    private var naturalSizes: [String: CGSize] = [:]       // "species|face"
    private var maskCache: [String: AlphaMask] = [:]

    /// On-screen height of a character, in points.
    private static let targetHeight: CGFloat = 97.5

    /// No sequence ships anywhere near this many frames; it's just a
    /// backstop so a scan can't run away if `Bundle.module` ever behaved
    /// unexpectedly.
    private static let maxFramesPerSequence = 100

    private static let logger = Logger(subsystem: "com.aakash.deskpet", category: "SpriteLibrary")

    private init() {
        for species in Species.all {
            for face in FaceVariant.allCases {
                let key = Self.key(species.id, face)
                let frames = Self.loadSequence(species: species.id, face: face, prefix: "idle")
                guard let first = frames.first, first.size.height > 0 else { continue }
                idleFrames[key] = frames

                let scale = Self.targetHeight / first.size.height
                naturalSizes[key] = CGSize(
                    width: (first.size.width * scale).rounded(),
                    height: Self.targetHeight
                )

                for gesture in Gesture.allCases {
                    let seq = Self.loadSequence(
                        species: species.id, face: face, prefix: gesture.resourcePrefix
                    )
                    if !seq.isEmpty {
                        gestureFrames["\(key)|\(gesture.rawValue)"] = seq
                    }
                }
            }
        }
    }

    private static func key(_ speciesID: String, _ face: FaceVariant) -> String {
        "\(speciesID)|\(face.rawValue)"
    }

    /// Checks the sprite resource bundle can actually be found, without
    /// touching `Bundle.module` — that accessor calls `fatalError()` on a
    /// miss, which is exactly the crash this guards against.
    ///
    /// SwiftPM's generated accessor only looks for `DeskPet_DeskPet.bundle`
    /// next to `Bundle.main.bundleURL` (the `.app` root) or at a
    /// dev-machine-only fallback baked in at build time; it never checks
    /// `Contents/Resources`, which is where `build_app.sh` actually copies
    /// it. So a correctly-assembled `.app` can still fail the generated
    /// lookup — check both locations ourselves.
    static func resourcesAvailable() -> Bool {
        let fm = FileManager.default
        let atBundleRoot = Bundle.main.bundleURL.appendingPathComponent("DeskPet_DeskPet.bundle")
        if fm.fileExists(atPath: atBundleRoot.path) { return true }
        if let resourceURL = Bundle.main.resourceURL {
            let atResources = resourceURL.appendingPathComponent("DeskPet_DeskPet.bundle")
            if fm.fileExists(atPath: atResources.path) { return true }
        }
        return false
    }

    func frames(for speciesID: String, face: FaceVariant) -> [NSImage] {
        idleFrames[Self.key(speciesID, face)] ?? []
    }

    func frames(for speciesID: String, face: FaceVariant, gesture: Gesture) -> [NSImage] {
        gestureFrames["\(Self.key(speciesID, face))|\(gesture.rawValue)"] ?? []
    }

    /// Gestures this species actually has art for in this face.
    func availableGestures(for speciesID: String, face: FaceVariant) -> [Gesture] {
        Gesture.allCases.filter { !frames(for: speciesID, face: face, gesture: $0).isEmpty }
    }

    /// Faces this species actually has art for.
    func availableFaces(for speciesID: String) -> [FaceVariant] {
        FaceVariant.allCases.filter { !frames(for: speciesID, face: $0).isEmpty }
    }

    /// Upright, unrotated on-screen size of the character.
    func naturalSize(for speciesID: String, face: FaceVariant) -> CGSize {
        naturalSizes[Self.key(speciesID, face)] ?? CGSize(width: 90, height: Self.targetHeight)
    }

    /// Opacity map of the oriented sprite, so clicks land only on the
    /// character and pass through everywhere else. Built on first use.
    /// Keyed by face too: the grin's tongue changes the silhouette.
    func hitMask(for speciesID: String, face: FaceVariant, edge: PeekEdge) -> AlphaMask? {
        let key = "\(Self.key(speciesID, face))|\(edge)"
        if let cached = maskCache[key] { return cached }
        guard let mask = buildMask(speciesID: speciesID, face: face, edge: edge) else { return nil }
        maskCache[key] = mask
        return mask
    }

    private func buildMask(speciesID: String, face: FaceVariant, edge: PeekEdge) -> AlphaMask? {
        guard let frame = frames(for: speciesID, face: face).first,
              let cgImage = frame.cgImage(forProposedRect: nil, context: nil, hints: nil)
        else { return nil }

        let natural = naturalSize(for: speciesID, face: face)
        let bounds = PeekOrientation.boundingSize(natural: natural, edge: edge)
        let width = max(1, Int(bounds.width.rounded()))
        let height = max(1, Int(bounds.height.rounded()))

        // A plain RGBA context keeps this portable; only the alpha byte
        // of each pixel is read back.
        let bytesPerPixel = 4
        let bytesPerRow = width * bytesPerPixel
        var buffer = [UInt8](repeating: 0, count: bytesPerRow * height)

        let ok: Bool = buffer.withUnsafeMutableBytes { raw -> Bool in
            guard let context = CGContext(
                data: raw.baseAddress,
                width: width,
                height: height,
                bitsPerComponent: 8,
                bytesPerRow: bytesPerRow,
                space: CGColorSpace(name: CGColorSpace.sRGB) ?? CGColorSpaceCreateDeviceRGB(),
                bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue
            ) else { return false }

            context.concatenate(PeekOrientation.maskTransform(natural: natural, edge: edge))
            context.draw(cgImage, in: CGRect(origin: .zero, size: natural))
            return true
        }
        guard ok else { return nil }

        // Core Graphics rows run bottom-up; flip so row 0 is the top and
        // sampling matches the view's coordinate space.
        var alpha = [UInt8](repeating: 0, count: width * height)
        for y in 0..<height {
            let sourceRow = (height - 1 - y) * bytesPerRow
            for x in 0..<width {
                alpha[y * width + x] = buffer[sourceRow + x * bytesPerPixel + 3]
            }
        }
        return AlphaMask(width: width, height: height, alpha: alpha)
    }

    // MARK: - Loading

    /// Loads every `<prefix>_NN.png` in the species/face subfolder, in order.
    private static func loadSequence(species: String, face: FaceVariant, prefix: String) -> [NSImage] {
        var frames: [NSImage] = []
        for i in 0..<maxFramesPerSequence {
            let name = String(format: "%@_%02d", prefix, i)
            guard let url = Bundle.module.url(
                forResource: name,
                withExtension: "png",
                subdirectory: "species/\(species)/\(face.rawValue)"
            ) else { break }
            guard let image = NSImage(contentsOf: url) else {
                logger.error("Could not decode sprite frame at \(url.path, privacy: .public)")
                continue
            }
            frames.append(image)
        }
        return frames
    }
}
